language: node_js
node_js:
  - node
  - lts/*
  - '10'
- sudo chown -R travis ./travis/pull_data.sh
- sudo chmod +x ./travis/pull_data.sh
- ./travis/pull_data.sh
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libsecret-1-dev
deploy:
  provider: npm
  skip_cleanup: true
  email: lakshmiravali.rimmalapudi@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$
    node: lts/*
